# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:

jobs:
  biased_lang:
    runs-on: ubuntu-latest
    name: Detecting Biased Language
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo $GITHUB_WORKSPACE
          docker pull ghcr.io/splunk/biased_lang:test
          docker run -v $GITHUB_WORKSPACE:/biased_lang -e GITHUB_URL=$GITHUB_SERVER_URL -e GITHUB_REPO=$GITHUB_REPOSITORY ghcr.io/splunk/biased_lang:test
